spell check on PDcontroller example
JacquesCarette/Drasil pull request #2403
Opened 2021-05-09 15:58 UTC by Awurama-N

closes Issue #2393

2021-05-09 16:44 UTC, JacquesCarette requested changes

2021-05-09 16:44 UTC, JacquesCarette commented on code/drasil-example/Drasil/PDController/Assumptions.hs
> +  = cic "damingCoeffSpring" aDampingCoeffDesc "Spring Damping Coeffecient"
That's better, but still not right...  Coefficient. In other places too.

2021-05-10 15:02 UTC, closed without merging

2021-05-10 17:50 UTC, balacij commented
@Awurama-N Are you still using the branch that you opened for this?

2021-05-10 17:56 UTC, Awurama-N commented
no i'm not using this branch, i started over from scratch,
i'll @ you on the one i'm using now