Add in rod NamedChunk for pendulum
JacquesCarette/Drasil pull request #2423
Opened 2021-05-11 15:25 UTC by Ant13731

Contributes to #2398

2021-05-11 18:40 UTC, JacquesCarette requested changes

2021-05-11 19:10 UTC, Ant13731 commented on code/drasil-example/Drasil/DblPendulum/Body.hs
> +  [S "The", phrase rod],
This is the only thing that has worked so far:
```Haskell
physSystParts = map foldlSent [[phraseNP (the rod)], [phraseNP (the mass)]]
```

2021-05-11 19:14 UTC, Ant13731 commented on code/drasil-example/Drasil/DblPendulum/Body.hs
> +  [S "The", phrase rod],
I just realized that foldlSent is probably the problem.

2021-05-11 19:24 UTC, Ant13731 commented
The new `physSysParts` function also removes the periods from the list (see the html/tex files for what I mean), which I think looks better anyway.

2021-05-11 19:49 UTC, JacquesCarette commented
We need to figure out where the period came from. Perhaps `foldlSent` did that?

2021-05-11 19:50 UTC, Ant13731 commented
Yes, `foldlSent` added the period at the end.

2021-05-11 20:09 UTC, JacquesCarette commented
I'm sure there's a combinator for terminating sentences. You most definitely should not be doing it "by hand".

2021-05-12 12:54 UTC, Ant13731 commented
The `+:+.` was the only combinator I could find that terminates sentences with a period. It takes two sentences, so `EmptyS` must be the first argument for it to work. When I'm changing `Utils.Drasil` later on, would it be good to add a combinator that takes one `Sentence` and just appends a period to it (that is, if I don't find an existing one)?

2021-05-12 13:43 UTC, JacquesCarette commented
Indeed, there is none.  Well, there is the private `wrap` in https://github.com/JacquesCarette/Drasil/blob/acf6d8dbd9632e14954e8e5027768edfd8ceb7d8/code/drasil-utils/Utils/Drasil/Fold.hs#L68-L76 which kind of does it, but it is not accessible, and is overkill.

I would be tempted to call it `:.` and used as a postfix operator - https://downloads.haskell.org/~ghc/8.8.4/docs/html/users_guide/glasgow_exts.html#postfix-operators.

2021-05-12 13:48 UTC, JacquesCarette approved these changes
I'll approve as is. A further PR can add the new combinator and fix this at the same time.
```
find drasil-example/ -type f -name '*.hs' -exec grep "\.\"" \{\} \; -print
```
finds a number of hard-coded periods in sentences that should be examined with this in mind.

2021-05-12 13:48 UTC, merged

2021-05-12 17:36 UTC, Ant13731 commented
I'm having a little bit of trouble incorporating `:.` as an operator. I looked it up and I think the `:` is reserved for data/type constructors, so implementing it as a function would be impossible. I also tried to use the postfixoperator language but I keep getting parse errors when trying to implement it. Is there an example of other postfix operators I could take a look at?
```
Parse error in pattern: (+.)
|
| ((+.) a) = a :+: S "."
|
```

2021-05-12 19:09 UTC, JacquesCarette commented
You did enable the `PostfixOperators` option in the compile options, right?

Indeed, I used bad syntax. The documentation above mentions left sections, documented at https://www.haskell.org/onlinereport/exps.html#sections .  One then needs to follow up into the lexical structure...

Cutting that short: `!.` or `$.` or `&.` should all work.  I think I prefer `!.`.

```haskell
(!.) a = a :+: S "."
```
**should** work.