Implementing new combinators into dblPendulum
JacquesCarette/Drasil pull request #2479
Opened 2021-05-18 17:30 UTC by Ant13731

Contributes #2399
Contributes #2476 
Implemented some higher level combinators in the pendulum example. I think `compoundNC` allows for a level 3 combination between `NamedIdeas`, but I had to place it into the database. Although I'm not sure if `Assumptions.hs` is the best place for it.

2021-05-18 21:32 UTC, JacquesCarette requested changes
Overall, good stuff. But as this is being edited, may as well do it 'right'.  Nice side-effect of fixing bad periods on the output.

2021-05-18 21:32 UTC, JacquesCarette commented on code/drasil-example/Drasil/DblPendulum/Assumptions.hs
> +pend2DMotionDesc = atStartNP (the (compoundNC pendulum motion)) `S.sIs` phrase twoD +:+. sParen (getAcc twoD)
it's probably not a good idea to use `compoundNC` inline like this. You should give this a Haskell-level name.

2021-05-18 21:32 UTC, JacquesCarette commented on code/drasil-example/Drasil/DblPendulum/Body.hs
> +                            S "it is useful to have a", phrase program, S "to simulate", phraseNP (motion
here too, this should be named. Same below.

2021-05-18 21:32 UTC, JacquesCarette commented on code/drasil-example/Drasil/DblPendulum/Concepts.hs
> +  ++ map nw defs ++ map nw [compoundNC pendulum motion,
aha, with all the previous things named, this list would then shorten!

2021-05-21 00:02 UTC, Ant13731 commented
This should be okay to merge now (and resolve the requested changes). I know we already discussed changing the naming scheme and moving some combinators in other issues, but I think it would be easier to just start on a fresh branch.

2021-05-21 01:57 UTC, JacquesCarette approved these changes

2021-05-21 01:57 UTC, merged