Add purpose double pendulum
JacquesCarette/Drasil pull request #2665
Opened 2021-07-08 18:39 UTC by cd155

- I created a references.hs file for double pendulum examples.
- moved some definitions to references.hs
- added algorithm in TermMap

After adding the purpose, there is one hyperlink that is missing, system constraints. The system constraints is a part of the General System Description which is missing in the double pendulum example. Do you think I should create a new ticket to add General System Description?

close #2631

2021-07-09 01:35 UTC, JacquesCarette requested changes
Mostly the changes are good, with the one exception.

2021-07-09 01:35 UTC, JacquesCarette commented on code/drasil-example/Drasil/DblPendulum/References.hs
> +hibbeler2004 :: Citation
This is not good - it represents duplication of the information that is in `Pendulum`. It was better the way it was before. Maybe take the opportunity to move this to `data-drasil`?

2021-07-09 18:32 UTC, cd155 reviewed
moved `hibbeler2004` into citations

2021-07-18 14:24 UTC, JacquesCarette approved these changes

2021-07-18 14:24 UTC, merged