Double Pendulum: update double pendulum theory
JacquesCarette/Drasil pull request #2782
Opened 2021-08-11 20:33 UTC by cd155

2021-08-12 21:34 UTC, JacquesCarette commented on code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Assumptions.hs
> +twoDMotion  = cic "twoDMotion"      twoDMotionDesc    "twoDMotion"    assumpDom
all the columns used to be nicely lined up - can you line them up again please?

2021-08-12 21:37 UTC, JacquesCarette requested changes
Just one tiny change to make, and this is good to go.

2021-08-12 21:37 UTC, JacquesCarette commented
and a master merge too.

2021-08-12 23:30 UTC, cd155 commented
@JacquesCarette Yes, those codes should be lined up now.

2021-08-12 23:38 UTC, JacquesCarette approved these changes

2021-08-12 23:39 UTC, JacquesCarette commented
Great, thanks. Except that now that I've merged more things, it needs another master merge!

2021-08-13 14:12 UTC, JacquesCarette approved these changes

2021-08-13 14:12 UTC, merged