3357 Issues with display of references - Suffix
JacquesCarette/Drasil pull request #3421
Opened 2023-05-12 15:05 UTC by harmanpreet-sagar

Contributes to #3357. Changes made to Helpers.hs in `drasil-printers` and stable to fix the suffixes of edition numbers.

2023-05-12 16:42 UTC, samm82 approved these changes

2023-05-12 16:42 UTC, samm82 commented on code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs
> +sufxer x = (++ ".") (sufx (mod x 10))
Wow! Good catch!

2023-05-12 17:24 UTC, harmanpreet-sagar commented
Yeah sure! I will make that change and update the PR!

2023-05-12 18:13 UTC, samm82 requested changes

2023-05-12 18:19 UTC, harmanpreet-sagar commented on code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs
> +    (++ ".") (sufx (mod x 10))
Makes sense! I will update that right now!

2023-05-12 18:43 UTC, samm82 approved these changes

2023-05-12 18:43 UTC, samm82 commented on code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs
> +    sufx (mod x 10))
Third time's a charm! Looks great 😁

2023-05-12 18:45 UTC, samm82 commented
I'm going to wait on merging this until I get a second opinion, just in case there's a more "Haskell-like" way of doing this I'm unaware of; @balacij what do you think of this?

2023-05-12 20:27 UTC, balacij commented
I think it would be good to use the [guarded syntax](learnyouahaskell.com/syntax-in-functions#guards-guards) for readability, but otherwise, it looks fine to me :smile:

2023-05-14 01:12 UTC, samm82 commented
@harmanpreet-sagar If there's a way to use guarded syntax that is still readable and maintains the functionality (which I'm sure there is), could you implement that? Otherwise, let me know and I'll merge this in.

2023-05-15 14:37 UTC, harmanpreet-sagar commented
@samm82 @balacij I have now modified the `sufxer` function to have a guarded syntax. Can you please review it and let me know if that is what you both meant by the guarded syntax or if there is any further change to the syntax or the function I should make?

2023-05-15 15:17 UTC, samm82 reviewed
After the space has been added and if it looks good to you @balacij, feel free to merge it!

2023-05-15 15:44 UTC, harmanpreet-sagar commented on code/drasil-printers/lib/Language/Drasil/Printing/Helpers.hs
> +    | otherwise = period(sufx (mod x 10))
Changed!

2023-05-16 02:41 UTC, balacij requested changes
```haskell
sufxer :: Int -> String
sufxer x = sufx r ++ "."
  where r = if x `elem` [11, 12, 13] then 0 else mod x 10
```

What do you think about something like this?

2023-05-16 13:14 UTC, harmanpreet-sagar commented
I like that! I will implement those right now.

2023-05-16 16:56 UTC, balacij approved these changes

2023-05-16 16:56 UTC, merged