Add citation to original (manual) works from each case study #3562 (Attempt 1)
JacquesCarette/Drasil pull request #3682
Opened 2023-12-16 06:36 UTC by daijingz

@balacij @smiths Hi Jason and Dr.Smith,
Because the `drasil-example` folder stores all regenerated examples, I think this is the right position to add the mentioned "back" citation. After checking inside folders, I did not find any README files. So the only correct place is in this README file.

Jason, There is one thing I did not find: Where is the Naveen's PD controller github address? I tried to search it before, but I did not find what I expected.

2024-01-04 14:32 UTC, JacquesCarette requested changes

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/topics/pd-controller repo.
This is not a valid link

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.
This is a bad link because Double Pendulum does not exist in that repo.

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies/gamephys repo.
Don't put raw links in the README, make them text links that point to the 'right' thing.

Also, don't name a directory a "repo". When you point to a sub-directory of a repo, say so.

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies/projectile repo.
You're pointing to projectile but this is ssp

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.
bad link

2024-01-04 14:32 UTC, JacquesCarette commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.
'template' was never a case study

2024-01-04 17:52 UTC, daijingz commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.
I just remove all changes here @JacquesCarette

2024-01-04 17:53 UTC, daijingz commented on code/drasil-example/README.md
> +    in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.
I just remove all changes here @JacquesCarette

2024-01-04 19:04 UTC, daijingz reviewed
@JacquesCarette Dr.Carette, I still have some confusions, but your requests has been mitigated mostly. Please look at my confusions.

2024-01-05 17:01 UTC, smiths commented
@daijingz the original version of double pendulum was created in a [repo](https://github.com/Zhang-Zhi-ZZ/CAS741Project) by Zhi Zhang.  You should use that link for your citation in the README file.  Specifically, you can point to the [SRS](https://github.com/Zhang-Zhi-ZZ/CAS741Project/blob/master/Double%20Pendulum/docs/SRS/SRS.pdf).

For pdcontroller, you can point to the original manually created [SRS from Naveen](https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.pdf).

You can point to the original (manually created) [SRS for ssp](https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/SRS/SRS.pdf).

You can point to the original [SRS for the solar water heating system with PCM (swhs)](https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf).

I've given links to the SRS in each case.  The original issue was to modify the introduction to the SRS to point to the original (manually created) case studies.  You are instead modifying the README file to point to the original case studies.  I like that idea.  We should eventually do both.  For now, we can focus on modifying the README file.  In the case of the README file, you should point to the repo, not the specific SRS.

@daijingz, if I have missed any of the case studies that you are looking for links to, please let me know.

2024-01-05 18:21 UTC, daijingz commented
@smiths There is one example you forget: 

> @daijingz the original version of double pendulum was created in a [repo](https://github.com/Zhang-Zhi-ZZ/CAS741Project) by Zhi Zhang. You should use that link for your citation in the README file. Specifically, you can point to the [SRS](https://github.com/Zhang-Zhi-ZZ/CAS741Project/blob/master/Double%20Pendulum/docs/SRS/SRS.pdf).
> 
> For pdcontroller, you can point to the original manually created [SRS from Naveen](https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.pdf).
> 
> You can point to the original (manually created) [SRS for ssp](https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/SRS/SRS.pdf).
> 
> You can point to the original [SRS for the solar water heating system with PCM (swhs)](https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf).
> 
> I've given links to the SRS in each case. The original issue was to modify the introduction to the SRS to point to the original (manually created) case studies. You are instead modifying the README file to point to the original case studies. I like that idea. We should eventually do both. For now, we can focus on modifying the README file. In the case of the README file, you should point to the repo, not the specific SRS.
> 
> @daijingz, if I have missed any of the case studies that you are looking for links to, please let me know.

@smiths There is one thing you forget: the `sglpend` example. I have checked some past students' CAS 741 projects, but I did not see any of them working with the single pendulum topic. -> That is why I did not have a good reference.

@smiths @JacquesCarette For the SRS references, I am working on it in the next attempt. However, I am unfamiliar with which part of code generates SRS. (I did some failing personal research before) Can you give me some quick hints about that?

2024-01-05 18:35 UTC, smiths commented
@daijingz you don't need a reference for the single pendulum example.  It was created in Drasil.  There was never (to my knowledge) a separate manual version.  It was created by @cd155 by modifying double pendulum.

2024-01-05 18:42 UTC, daijingz commented
> @daijingz you don't need a reference for the single pendulum example. It was created in Drasil. There was never (to my knowledge) a separate manual version. It was created by @cd155 by modifying double pendulum.

@smiths @JacquesCarette I think now I have completed (the first step), please take a look. For `sglpend`, I just removed the inappropriate reference.

2024-01-05 18:51 UTC, smiths commented on code/drasil-example/README.md
> +    in the [Projectile](https://github.com/smiths/caseStudies/tree/master/CaseStudies/projectile) motion analysis example.
There are multiple versions of projectile.  You should point to the following version:

https://github.com/smiths/caseStudies/tree/master/CaseStudies/projectile/projectileSRS

2024-01-05 18:53 UTC, smiths commented on code/drasil-example/README.md
> +  - This is a recreation of the original, manually-created version
Through all of the examples you should say [recreation vs re-creation](https://www.google.com/search?q=recreation+vs+re-creation&sca_esv=596015288&rlz=1C5CHFA_enCA763CA763&sxsrf=ACQVn096xoPk__UIQtoMCtNGPndrSxnRMw%3A1704480735154&ei=30-YZYGJCd2B0PEPm82CyAU&oq=recreation+versus+re&gs_lp=Egxnd3Mtd2l6LXNlcnAiFHJlY3JlYXRpb24gdmVyc3VzIHJlKg0IABAAGIAEGIoFGJECMgsQABiABBiKBRiRAjIHEAAYgAQYCjIGEAAYFhgeSMUaUNEDWIkMcAF4AZABAJgBZaABtgaqAQM5LjG4AQHIAQD4AQHCAgoQABhHGNYEGLADwgINEAAYRxjWBBjJAxiwA8ICDhAAGIAEGIoFGJIDGLADwgINEAAYgAQYigUYQxiwA8ICEBAAGIAEGIoFGEMYsQMYyQPCAgsQABiABBiKBRiSA8ICDRAAGIAEGIoFGEMYsQPCAgoQABiABBiKBRhDwgIFEAAYgATCAg4QABiABBiKBRixAxiDAcICBRAuGIAEwgILEC4YgAQYxwEYrwHCAgoQABgWGB4YDxgKwgIIEAAYFhgeGAriAwQYACBBiAYBkAYK&sclient=gws-wiz-serp).

2024-01-05 18:55 UTC, smiths commented
I've added comments while [reviewing the README file](https://github.com/JacquesCarette/Drasil/pull/3682/files).

2024-01-05 18:58 UTC, daijingz commented
> I've added comments while [reviewing the README file](https://github.com/JacquesCarette/Drasil/pull/3682/files).

@smiths resolve all your mentioned issues.

2024-01-05 19:01 UTC, smiths commented
The changes look fine to me, but @JacquesCarette is the final authority on all pull requests.  Assuming this PR is accepted, we shouldn't close the original issue, since we still would like to modify the generator so that the SRS files have the required citations.

2024-01-05 19:22 UTC, daijingz commented
Then in the second step, I have a lot of confusion too: 
After opening `body.hs` files (the right files we should change), I am confused with which part of the section we should include this citation. I think the correct place is a reference (the last part), then there is another question: some reference sections are empty, should we establish a new section, and then add the designated citation inside?

The third question is, what should we write inside the SRS file? I guess we need to write the same thing as what we did in the README file. 

@JacquesCarette @smiths Dr.Carette and Dr.Smith, if you have any extra requirements, please let me know as soon as possible.

2024-01-05 19:54 UTC, smiths commented
@daijingz now that you know what studies to cite, @balacij should be able to help you with where to add this information to the DSLs for the generator to use.

2024-01-06 04:06 UTC, daijingz commented
#3415 has similar places to edit. To utilize time better, I just work on that issue until I get further information.

2024-01-06 13:35 UTC, JacquesCarette approved these changes

2024-01-06 13:35 UTC, merged

2024-01-06 15:23 UTC, cd155 commented
Olu actually made the single pendulum example. @smiths

2024-01-06 15:30 UTC, smiths commented
Thank you @cd155.  You are correct.