Wiki: Add page for Benefits of Drasil
JacquesCarette/Drasil pull request #3779
Opened 2024-06-06 14:46 UTC by BilalM04

Created a wiki page for the benefits of Drasil to list examples that showcase the power of generative programming within Drasil.

Closes #3778

2024-06-06 14:47 UTC, BilalM04 commented
@B-rando1 feel free to make any changes as you see fit.

2024-06-06 14:53 UTC, smiths approved these changes
Thank you @BilalM04.  This exactly what I was looking for.  I like the positive tone for introductory blub.  I'll approve, but wait for @JacquesCarette to review before merging.

2024-06-06 20:59 UTC, JacquesCarette requested changes

2024-06-06 20:59 UTC, JacquesCarette commented on wiki/Benefits-of-Drasil.md
> +Welcome to the Benefits of Drasil wiki page! This page is dedicated to showcasing the transformative impact of generative programming within Drasil. In this wiki, you'll find a growing collection of
Let's not start pages with "Welcome" statements that are furthermore self-referential (i.e. 'this page', 'this wiki'). Please rephrase to remove these self-referential statements.

2024-06-06 20:59 UTC, JacquesCarette commented on wiki/Benefits-of-Drasil.md
> +**Pull Request [#3772](../issues/3772)**: This PR addresses issue [#3732](../issues/3732), where the generated code files were missing an empty line between the header comment block and the start of
Please invert the 'story': put the benefits first, and how this was achieved second.

2024-06-07 13:46 UTC, JacquesCarette requested changes

2024-06-07 13:46 UTC, JacquesCarette commented on wiki/Benefits-of-Drasil.md
> +The Benefits of Drasil wiki page is dedicated to showcasing the transformative impact of generative programming within Drasil. It features a growing collection of examples demonstrating how Drasil's
Definitely better, but still in the passive voice.

Drasil's use of generative programming has a transformative impact on the development process. Here we collect examples demonstrating [rest the same]

2024-06-07 13:46 UTC, JacquesCarette commented on wiki/Benefits-of-Drasil.md
> +**Pull Request [#3772](../issues/3772)**: Generative programming streamlined the refactoring process, eliminating the need for 175 manual edits. This PR addresses issue [#3732](../issues/3732), where
**[Cosmetic changes made easy](../issues/3772)**: Our generated code was missing an empty line between the header comment block and the start of the code. A one-line change fixed this issue; at the time of this changes, this resulted in updates to 175 files, i.e. eliminating the need for 175 manual edits.

2024-06-07 14:45 UTC, JacquesCarette approved these changes

2024-06-07 14:45 UTC, merged