Fix Drasil Contributor's Guide links
JacquesCarette/Drasil pull request #3819
Opened 2024-06-25 02:58 UTC by NoahCardoso

I found all the bad links in the contributor's guide. There were only the two bad links that Mr. Smith mentioned in #3816. Closes #3816

2024-06-27 03:06 UTC, balacij requested changes

2024-06-27 03:06 UTC, balacij commented on wiki/Contributor's-Guide.md
> +One of the most important things in working with Drasil is having a solid foundation for using GitHub. Read through [Git2Know](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil) to le
I think you can omit the `https://..../` part -- we should only need `Git2Know-for-Drasil`, no?

2024-06-27 16:23 UTC, balacij approved these changes
LGTM! Thank you!

2024-06-29 06:10 UTC, JacquesCarette approved these changes

2024-06-29 06:10 UTC, merged