#3252 Sentence Reworking
JacquesCarette/Drasil pull request #3901
Opened 2024-08-01 04:38 UTC by daijingz

1.Split some long sentences
2. Use defined concepts in the sentences.

2024-08-01 19:23 UTC, JacquesCarette requested changes
A lot of these really are not worthwhile improvements. You need to think harder.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Assumptions.hs
> +cartSysRDesc = atStartNP (the cartesian) `S.is` S "right-handed" +:+ S "where" +:+
This change is not an improvement, please remove. If it used a combinator, it would have been, but this is just splitting English text needlessly.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Assumptions.hs
> +yAxisDirDesc = atStartNP (direction `the_ofThe` yAxis) `S.is` S "directed opposite" +:+ S "to" +:+. phrase gravity
This is similarly not useful.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
> +purp = foldlSent_ [S "predict", S "the", phrase motion `S.ofA` S "double", phrase pendulum]
If you had used the combinator `the`, this would have been good, but this is not.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
> +                            S "attached" `S.toThe` S "end" `S.ofA` phrase rod `S.andIts` S "moving curve" `S.is`
This is minimalistically an improvement.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
> +                            S "it" `S.is` S "useful to have a", phrase program, S "to simulate", phraseNP (motion
This isn't worth it! (Same for the next one).

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
> +  physical) +:+ S "state" `S.ofThe` phrase motion `S.andThe` plural inDatum +:+ S "related" +:+
If `state` was a phrase, this split would have been useful. This is not. The `S.andThe` is fine.

2024-08-01 19:23 UTC, JacquesCarette commented on code/drasil-example/dblpend/lib/Drasil/DblPend/Body.hs
> +  phrase problem +:+ S "input" +:+ S "to the" +:+. phrase software]
not useful

2024-08-02 02:39 UTC, daijingz commented
Fixed. There are two places I am not uncertain:
`S "are appropriate" `S.for` S "any particular"`
AND
`atStartNP (the program), S "documented here" `S.is` S "called", phrase prog]`

@JacquesCarette On both lines, I tried to use `phrase` to represent both sides of the combinator, however, I failed with errors. (If you feel it is not worth it, I can withdraw my updates.)

Another thing is the Drasil-generated examples do not have many sentences inside, and while there are rigid improvement requirements, only a few places are available for changes. Here I include some "seemly-non-worthy" improvements, just aims to maximize the number of improvement places.

2024-09-11 16:59 UTC, closed without merging