Updated range in Julia
JacquesCarette/Drasil pull request #3994
Opened 2024-12-31 17:55 UTC by B-rando1

Julia's ranges include the end value, and other languages don't. I updated the Julia renderer to subtract `1` from the end value to match the other languages.

Note that while this fixes it for positive `step` values, it does not for negative `step` values. More work needs to be done here.

Contributes to #3992

2024-12-31 18:05 UTC, B-rando1 commented
I'm not sure what's going on with HLint. The error in the log is `E: Unable to locate package libtinfo5`.

2025-01-01 17:06 UTC, JacquesCarette requested changes

2025-01-01 17:06 UTC, JacquesCarette commented on code/stable/gooltest/julia/VectorTest/VectorTest.jl
> +for i in 0:1:length(v1) - 1 - 1
This seems odd -- length - 2 ?  This looks like it is over-compensating!

2025-01-01 17:47 UTC, B-rando1 commented on code/stable/gooltest/julia/VectorTest/VectorTest.jl
> +for i in 0:1:length(v1) - 1 - 1
Good catch. I should have noticed that. It looks like I accounted for the range difference in the `thunkAssign` function, which uses the `forRange` function. Because this change is upstream of it (most likely the 'correct' place), it was affected. My new commit should remedy that.

2025-01-01 20:15 UTC, JacquesCarette approved these changes
I'm approving now, but won't merge in quite yet, as the linter did not run -l ooks like an upstream problem though, i.e. not your fault.

2025-01-01 20:52 UTC, JacquesCarette commented
#3998 should fix that, but I'm waiting for a review.

2025-06-08 19:12 UTC, balacij approved these changes
Pending the CI, this PR LGTM!

2025-06-09 14:53 UTC, JacquesCarette approved these changes

2025-06-09 14:53 UTC, merged